const routes = require('next-routes')
                                                    
module.exports = routes()
.add('index')
.add('searchAll',           '/adventures', 'search/index')
.add('searchDestination',   '/adventures/:destination', 'search/index')
.add('searchAdventure',     '/adventures/:destination/:adventure', 'search/index')
.add('searchActivity',      '/adventures/:destination/:adventure/:activity', 'search/index')
.add('detail',              '/adventures/:destination/:adventure/:tour/:uuid', 'detail/index')
.add('reserve',             '/reservations/:uuid', 'reserve/index')
.add('reserveSuccess',      '/reservation_success', 'reserve/success')
.add('about_us',            '/about_us', 'about_us/index')
.add('contact',             '/contact', 'contact/index')
.add('subscribe',           '/subscribe', 'subscribe/index')
.add('terms',               '/extras/terms/', 'terms/index')
.add('privacy',             '/extras/privacy/', 'privacy/index')

.add('langing1',            '/buceo-en-cancun/', 'landings/landing1')
.add('langing2',            '/buceo-en-cozumel/', 'landings/landing2')
.add('langing3',            '/buceo-en-playa-del-carmen/', 'landings/landing3')